mutation {
  addColumn(input: TEST_INPUT) {
    column {
      id
      name
      mainTasks {
        description
        id
        status
        title
        subTasks {
          id
          isCompleted
          title
        }
      }
    }
  }
}