mutation {
    deleteSubTask(input: TEST_INPUT) {
        mainTask {
            description
            id
            status
            title
            subTasks {
                id
                isCompleted
                title
            }
        }
    }
}