services:
  kaban:
    container_name: kaban
    image: kaban:latest
    restart: always
    ports:
      - 5264:5264
      - 7001:7001
    secrets:
      - KABANDBCONNECTIONSTRING
      - DISCORD_CLIENT_ID
      - DISCORD_SECRET

networks:
  default:
    external: true
    name: nginxproxymanager_default
    
secrets:
  KABANDBCONNECTIONSTRING:
    environment: "KABANDBCONNECTIONSTRING"
  DISCORD_CLIENT_ID:
    environment: "DISCORD_CLIENT_ID"
  DISCORD_SECRET:
    environment: "DISCORD_SECRET"